name: bionic_eye
description: "Describe images using Gemini"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  camerawesome: ^2.0.1
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_settings_screens: ^0.3.4
  google_generative_ai: ^0.4.0
  mime: ^1.0.5
  shared_preferences: ^2.2.3
  super_clipboard: ^0.8.13
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
